kind: Pod   ## kubectl api-resources
apiVersion: v1 ## kubectl explain pod
metadata:
  name: mypod
  labels:
    env: dev
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
